// AUTO-GENERATED by tools/sdk-codegen — do not edit by hand.

package co.commet.resources;

import co.commet.ApiResponse;
import co.commet.CommetHttpClient;
import co.commet.models.DeletedObject;
import co.commet.models.Feature;
import co.commet.models.FeatureAccess;
import co.commet.models.FeatureLookup;
import co.commet.params.CanUseFeatureParams;
import co.commet.params.CreateFeatureParams;
import co.commet.params.GetFeatureAccessParams;
import co.commet.params.ListFeaturesParams;
import co.commet.params.UpdateFeatureParams;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.List;

import static co.commet.CommetHttpClient.buildBody;

public class FeaturesResource {

    private final CommetHttpClient http;

    public FeaturesResource(CommetHttpClient http) {
        this.http = http;
    }

    /**
     * List all features for a customer's active subscription.
     */
    public ApiResponse<List<FeatureAccess>> list(ListFeaturesParams params) {
        return http.get("/features", buildBody(
                "customer_id", params.getCustomerId()
        ), new TypeReference<>() {});
    }

    /**
     * Get feature access details. Use action=canUse to check if customer can consume one more unit.
     */
    public ApiResponse<FeatureLookup> get(String code, GetFeatureAccessParams params) {
        return http.get("/features/" + code, buildBody(
                "customer_id", params.getCustomerId(),
                "action", params.getAction()
        ), new TypeReference<>() {});
    }

    /**
     * Get feature access details. Use action=canUse to check if customer can consume one more unit.
     */
    public ApiResponse<FeatureLookup> canUse(String code, CanUseFeatureParams params) {
        return http.get("/features/" + code, buildBody(
                "customer_id", params.getCustomerId(),
                "action", "canUse"
        ), new TypeReference<>() {});
    }

    /**
     * Create a new feature. Code must be lowercase alphanumeric with underscores.
     */
    public ApiResponse<Feature> create(CreateFeatureParams params) {
        return http.post("/features/manage", buildBody(
                "name", params.getName(),
                "code", params.getCode(),
                "type", params.getType(),
                "description", params.getDescription(),
                "unit_name", params.getUnitName()
        ), params.getIdempotencyKey(), new TypeReference<>() {});
    }

    /**
     * Update a feature's name, description, or unit name. At least one field must be provided.
     */
    public ApiResponse<Feature> update(String code, UpdateFeatureParams params) {
        return http.put("/features/" + code + "/manage", buildBody(
                "name", params.getName(),
                "description", params.getDescription(),
                "unit_name", params.getUnitName()
        ), params.getIdempotencyKey(), new TypeReference<>() {});
    }

    /**
     * Delete a feature. Fails if the feature is attached to active plans or has an active add-on.
     */
    public ApiResponse<DeletedObject> delete(String code) {
        return http.delete("/features/" + code + "/manage", null, new TypeReference<>() {});
    }
}
