// AUTO-GENERATED by tools/sdk-codegen — do not edit by hand.

package co.commet.resources;

import co.commet.ApiResponse;
import co.commet.CommetHttpClient;
import co.commet.models.CreatedInvoice;
import co.commet.models.Invoice;
import co.commet.models.InvoiceDownload;
import co.commet.models.InvoiceStatus;
import co.commet.models.SentInvoice;
import co.commet.params.CreateAdjustmentInvoiceParams;
import co.commet.params.ListInvoicesParams;
import co.commet.params.SendInvoiceParams;
import co.commet.params.UpdateInvoiceStatusParams;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.List;
import java.util.Map;

import static co.commet.CommetHttpClient.buildBody;

public class InvoicesResource {

    private final CommetHttpClient http;

    public InvoicesResource(CommetHttpClient http) {
        this.http = http;
    }

    /**
     * List invoices with cursor-based pagination. Filter by customer, status, or subscription.
     */
    public ApiResponse<List<Invoice>> list(ListInvoicesParams params) {
        return http.get("/invoices", buildBody(
                "customer_id", params.getCustomerId(),
                "status", params.getStatus(),
                "subscription_id", params.getSubscriptionId(),
                "cursor", params.getCursor(),
                "limit", params.getLimit()
        ), new TypeReference<>() {});
    }

    /**
     * Retrieve a single invoice by its public ID, including line items.
     */
    public ApiResponse<Invoice> get(String id) {
        return http.get("/invoices/" + id, new TypeReference<>() {});
    }

    /**
     * Create a one-off adjustment invoice. Use a negative amount for a credit.
     */
    public ApiResponse<CreatedInvoice> createAdjustment(CreateAdjustmentInvoiceParams params) {
        return http.post("/invoices", buildBody(
                "customer_id", params.getCustomerId(),
                "amount", params.getAmount(),
                "description", params.getDescription(),
                "metadata", params.getMetadata()
        ), params.getIdempotencyKey(), new TypeReference<>() {});
    }

    /**
     * Generate a signed URL to download the invoice as a PDF. The URL expires after 7 days.
     */
    public ApiResponse<InvoiceDownload> getDownloadUrl(String id) {
        return http.get("/invoices/" + id + "/download", new TypeReference<>() {});
    }

    /**
     * Send the invoice to the customer via email.
     */
    public ApiResponse<SentInvoice> send(String id, SendInvoiceParams params) {
        return http.post("/invoices/" + id + "/send", Map.of(), params.getIdempotencyKey(), new TypeReference<>() {});
    }

    /**
     * Mark an outstanding invoice as "paid" or "void". Cannot change the status of already paid or voided invoices.
     */
    public ApiResponse<InvoiceStatus> updateStatus(String id, UpdateInvoiceStatusParams params) {
        return http.put("/invoices/" + id + "/status", buildBody(
                "status", params.getStatus()
        ), params.getIdempotencyKey(), new TypeReference<>() {});
    }
}
