// AUTO-GENERATED by tools/sdk-codegen — do not edit by hand.

package co.commet.resources;

import co.commet.ApiResponse;
import co.commet.CommetHttpClient;
import co.commet.models.Payout;
import co.commet.models.PayoutBankAccount;
import co.commet.models.PayoutVerification;
import co.commet.params.AddPayoutBankAccountParams;
import co.commet.params.CompletePayoutVerificationParams;
import co.commet.params.RequestPayoutParams;
import com.fasterxml.jackson.core.type.TypeReference;

import static co.commet.CommetHttpClient.buildBody;

public class PayoutsResource {

    private final CommetHttpClient http;

    public PayoutsResource(CommetHttpClient http) {
        this.http = http;
    }

    /**
     * Add an additional destination bank account to the organization's existing payout account. Country and currency are resolved from the organization. The full account number is never returned — only `last4`.
     */
    public ApiResponse<PayoutBankAccount> addBankAccount(AddPayoutBankAccountParams params) {
        return http.post("/payouts/bank-accounts", buildBody(
                "account_number", params.getAccountNumber(),
                "account_holder_name", params.getAccountHolderName(),
                "routing_number", params.getRoutingNumber(),
                "account_type", params.getAccountType(),
                "set_default", params.getSetDefault()
        ), params.getIdempotencyKey(), new TypeReference<>() {});
    }

    /**
     * Withdraw available balance to the organization's verified payout account. `amount` is in cents (USD, minimum 1000 = $10). The payout is created in `pending` and settles to `paid` asynchronously as provider webhooks arrive.
     */
    public ApiResponse<Payout> request(RequestPayoutParams params) {
        return http.post("/payouts", buildBody(
                "amount", params.getAmount(),
                "description", params.getDescription()
        ), params.getIdempotencyKey(), new TypeReference<>() {});
    }

    /**
     * Provision the organization's payout account in a single call with the full KYC + bank payload. Uploads the identity document, persists the destination bank, and creates the connected account through the org's payout provider. The account starts `pending_verification` and flips to `verified` via the provider's webhook. Idempotent: returns the existing account if the org already has one.
     */
    public ApiResponse<PayoutVerification> completeVerification(CompletePayoutVerificationParams params) {
        return http.post("/payouts/verification", buildBody(
                "email", params.getEmail(),
                "business_type", params.getBusinessType(),
                "business_url", params.getBusinessUrl(),
                "document_url", params.getDocumentUrl(),
                "bank", params.getBank(),
                "individual", params.getIndividual(),
                "company", params.getCompany()
        ), params.getIdempotencyKey(), new TypeReference<>() {});
    }
}
