// AUTO-GENERATED by tools/sdk-codegen — do not edit by hand.

package co.commet.resources;

import co.commet.ApiResponse;
import co.commet.CommetHttpClient;
import co.commet.models.AddedPlanToGroup;
import co.commet.models.DeletedObject;
import co.commet.models.PlanGroup;
import co.commet.models.RemovedPlanFromGroup;
import co.commet.models.ReorderedPlans;
import co.commet.params.AddPlanToGroupParams;
import co.commet.params.CreatePlanGroupParams;
import co.commet.params.ListPlanGroupsParams;
import co.commet.params.ReorderPlansInGroupParams;
import co.commet.params.UpdatePlanGroupParams;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.List;

import static co.commet.CommetHttpClient.buildBody;

public class PlanGroupsResource {

    private final CommetHttpClient http;

    public PlanGroupsResource(CommetHttpClient http) {
        this.http = http;
    }

    /**
     * List plan groups with cursor-based pagination.
     */
    public ApiResponse<List<PlanGroup>> list(ListPlanGroupsParams params) {
        return http.get("/plan-groups", buildBody(
                "limit", params.getLimit(),
                "cursor", params.getCursor()
        ), new TypeReference<>() {});
    }

    /**
     * Retrieve a plan group by ID, including its plans ordered by sortOrder.
     */
    public ApiResponse<PlanGroup> get(String id) {
        return http.get("/plan-groups/" + id, new TypeReference<>() {});
    }

    /**
     * Create a new plan group for organizing plans.
     */
    public ApiResponse<PlanGroup> create(CreatePlanGroupParams params) {
        return http.post("/plan-groups", buildBody(
                "name", params.getName(),
                "description", params.getDescription(),
                "is_public", params.getIsPublic()
        ), params.getIdempotencyKey(), new TypeReference<>() {});
    }

    /**
     * Update a plan group's name, description, or visibility.
     */
    public ApiResponse<PlanGroup> update(String id, UpdatePlanGroupParams params) {
        return http.put("/plan-groups/" + id, buildBody(
                "name", params.getName(),
                "description", params.getDescription(),
                "is_public", params.getIsPublic()
        ), params.getIdempotencyKey(), new TypeReference<>() {});
    }

    /**
     * Delete a plan group. Plans in the group are unlinked, not deleted.
     */
    public ApiResponse<DeletedObject> delete(String id) {
        return http.delete("/plan-groups/" + id, null, new TypeReference<>() {});
    }

    /**
     * Add an existing plan to a plan group with optional sort order.
     */
    public ApiResponse<AddedPlanToGroup> addPlan(String id, AddPlanToGroupParams params) {
        return http.post("/plan-groups/" + id + "/plans", buildBody(
                "plan_id", params.getPlanId(),
                "sort_order", params.getSortOrder()
        ), params.getIdempotencyKey(), new TypeReference<>() {});
    }

    /**
     * Remove a plan from a plan group.
     */
    public ApiResponse<RemovedPlanFromGroup> removePlan(String id, String planId) {
        return http.delete("/plan-groups/" + id + "/plans/" + planId, null, new TypeReference<>() {});
    }

    /**
     * Set the display order of plans within a group. All plan IDs in the group must be provided.
     */
    public ApiResponse<ReorderedPlans> reorderPlans(String id, ReorderPlansInGroupParams params) {
        return http.put("/plan-groups/" + id + "/plans/reorder", buildBody(
                "plan_ids", params.getPlanIds()
        ), params.getIdempotencyKey(), new TypeReference<>() {});
    }
}
