// AUTO-GENERATED by tools/sdk-codegen — do not edit by hand.

package co.commet.resources;

import co.commet.ApiResponse;
import co.commet.CommetHttpClient;
import co.commet.models.PromoCode;
import co.commet.params.CreatePromoCodeParams;
import co.commet.params.ListPromoCodesParams;
import co.commet.params.UpdatePromoCodeParams;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.List;

import static co.commet.CommetHttpClient.buildBody;

public class PromoCodesResource {

    private final CommetHttpClient http;

    public PromoCodesResource(CommetHttpClient http) {
        this.http = http;
    }

    /**
     * List promo codes with cursor-based pagination.
     */
    public ApiResponse<List<PromoCode>> list(ListPromoCodesParams params) {
        return http.get("/promo-codes", buildBody(
                "limit", params.getLimit(),
                "cursor", params.getCursor()
        ), new TypeReference<>() {});
    }

    /**
     * Retrieve a promo code by its public ID.
     */
    public ApiResponse<PromoCode> get(String id) {
        return http.get("/promo-codes/" + id, new TypeReference<>() {});
    }

    /**
     * Create a new promo code. Optionally restrict to specific plans.
     */
    public ApiResponse<PromoCode> create(CreatePromoCodeParams params) {
        return http.post("/promo-codes", buildBody(
                "code", params.getCode(),
                "discount_type", params.getDiscountType(),
                "discount_value", params.getDiscountValue(),
                "duration_cycles", params.getDurationCycles(),
                "max_redemptions", params.getMaxRedemptions(),
                "expires_at", params.getExpiresAt(),
                "plan_ids", params.getPlanIds()
        ), params.getIdempotencyKey(), new TypeReference<>() {});
    }

    /**
     * Update a promo code's redemption limits, expiration, active status, or plan restrictions.
     */
    public ApiResponse<PromoCode> update(String id, UpdatePromoCodeParams params) {
        return http.put("/promo-codes/" + id, buildBody(
                "max_redemptions", params.getMaxRedemptions(),
                "expires_at", params.getExpiresAt(),
                "active", params.getActive(),
                "plan_ids", params.getPlanIds()
        ), params.getIdempotencyKey(), new TypeReference<>() {});
    }
}
