// AUTO-GENERATED by tools/sdk-codegen — do not edit by hand.

package co.commet.resources;

import co.commet.ApiResponse;
import co.commet.CommetHttpClient;
import co.commet.models.UsageQuota;
import co.commet.models.UsageQuotaEvent;
import co.commet.params.AddQuotaParams;
import co.commet.params.GetAllQuotaAllowancesParams;
import co.commet.params.GetQuotaAllowanceParams;
import co.commet.params.RemoveQuotaParams;
import co.commet.params.SetQuotaParams;
import com.fasterxml.jackson.core.type.TypeReference;
import java.util.List;

import static co.commet.CommetHttpClient.buildBody;

public class QuotaResource {

    private final CommetHttpClient http;

    public QuotaResource(CommetHttpClient http) {
        this.http = http;
    }

    /**
     * Add to a customer's quota allowance for a feature. Defaults to 1 if count is omitted.
     */
    public ApiResponse<UsageQuotaEvent> add(AddQuotaParams params) {
        return http.post("/usage/quota", buildBody(
                "customer_id", params.getCustomerId(),
                "external_id", params.getExternalId(),
                "feature_code", params.getFeatureCode(),
                "count", params.getCount()
        ), params.getIdempotencyKey(), new TypeReference<>() {});
    }

    /**
     * Set a customer's quota allowance for a feature to an exact value.
     */
    public ApiResponse<UsageQuotaEvent> set(SetQuotaParams params) {
        return http.put("/usage/quota", buildBody(
                "customer_id", params.getCustomerId(),
                "external_id", params.getExternalId(),
                "feature_code", params.getFeatureCode(),
                "count", params.getCount()
        ), params.getIdempotencyKey(), new TypeReference<>() {});
    }

    /**
     * Remove from a customer's quota allowance for a feature. Defaults to 1 if count is omitted. Returns 400 insufficient_balance if the balance would go negative.
     */
    public ApiResponse<UsageQuotaEvent> remove(RemoveQuotaParams params) {
        return http.delete("/usage/quota", buildBody(
                "customer_id", params.getCustomerId(),
                "external_id", params.getExternalId(),
                "feature_code", params.getFeatureCode(),
                "count", params.getCount()
        ), params.getIdempotencyKey(), new TypeReference<>() {});
    }

    /**
     * Get the current quota allowance (used vs included) for a specific feature.
     */
    public ApiResponse<UsageQuota> get(GetQuotaAllowanceParams params) {
        return http.get("/usage/quota", buildBody(
                "customer_id", params.getCustomerId(),
                "feature_code", params.getFeatureCode()
        ), new TypeReference<>() {});
    }

    /**
     * Get all quota allowances for a customer across every quota feature in their plan.
     */
    public ApiResponse<List<UsageQuota>> getAll(GetAllQuotaAllowancesParams params) {
        return http.get("/usage/quota/all", buildBody(
                "customer_id", params.getCustomerId()
        ), new TypeReference<>() {});
    }
}
